// frontend/src/lib/tiles/operations.test.ts
import { emptyLayout } from './types';
import type { TileGroup, TileLayout } from './types';
import { splitOut, moveTab, allowedEdges, tileOf } from './operations';

function assert(cond: boolean, msg: string) {
  if (!cond) throw new Error('FAIL: ' + msg);
}
function tile(id: string, tabs: string[]): TileGroup {
  return { id, tabs: [...tabs], activeTabId: tabs[0] ?? '' };
}
function layout(tiles: TileGroup[], orientation: 'h' | 'v' = 'h'): TileLayout {
  return { tiles, orientation, activeTileId: tiles[0].id, dividers: { main: 0.5, cross: 0.5 } };
}

// 1 -> 2: dragging s1 to the right of the single tile
const l1 = layout([tile('A', ['s1', 's2', 's3', 's4'])]);
const l2 = splitOut(l1, 's1', 'A', 'right');
assert(l2.tiles.length === 2 && l2.orientation === 'h', '1->2 makes 2 h tiles');
assert(l2.tiles[0].id === 'A' && l2.tiles[1].tabs.join() === 's1', '1->2 existing stays slot0, moved slot1');

// 1 -> 2 top => vertical, moved goes first
const l2v = splitOut(l1, 's1', 'A', 'top');
assert(l2v.orientation === 'v' && l2v.tiles[0].tabs.join() === 's1', '1->2 top = vertical, moved slot0');

// cannot split a lone-tab tile
const lone = layout([tile('A', ['s1'])]);
assert(splitOut(lone, 's1', 'A', 'right') === lone, 'lone tab split is no-op');

// allowedEdges at n=2 = all four edges (perpendicular subdivides into a T,
// a source-emptying drop re-orients the two tiles)
const twoH = l2; // A=[s2,s3,s4], B=[s1]
assert(allowedEdges(twoH, 'A').join() === 'left,right,top,bottom', 'n2 allows all edges');

// Re-orientation: two single-tab tiles, dragging one to the opposite axis flips
// the layout while keeping 2 tiles (the source tile empties and collapses).
const sideBySide = layout([tile('A', ['s1']), tile('B', ['s2'])], 'h');
const stacked = splitOut(sideBySide, 's1', 'B', 'bottom');
assert(stacked.tiles.length === 2, 'reorient keeps 2 tiles');
assert(stacked.orientation === 'v', 'reorient flips h -> v');
assert(stacked.tiles[0].tabs.join() === 's2' && stacked.tiles[1].tabs.join() === 's1', 'moved tab sits on dropped (bottom) edge');

// Re-orientation the other way: stacked -> side-by-side by dragging to an edge.
const backToRow = splitOut(stacked, 's2', stacked.tiles[1].id, 'left');
assert(backToRow.tiles.length === 2 && backToRow.orientation === 'h', 'reorient flips v -> h');
assert(backToRow.tiles[0].tabs.join() === 's2', 'moved tab sits on dropped (left) edge');

// A multi-tab source with a same-axis drop has no canonical 3-tile form -> no-op.
assert(splitOut(twoH, 's2', 'A', 'left') === twoH, 'n2 same-axis multi-tab drop is no-op');

// 2 -> 3 : drop s2 on bottom of A (left column subdivides; the untouched
// tile — the one holding s1, id generated by the earlier split — stays full slot0)
const untouched = twoH.tiles.find((t) => t.tabs.includes('s1'))!;
const l3 = splitOut(twoH, 's2', 'A', 'bottom');
assert(l3.tiles.length === 3, '2->3 makes 3 tiles');
assert(l3.tiles[0].id === untouched.id, '2->3 untouched tile becomes full slot0');
assert(tileOf(l3, 's2')!.tabs.join() === 's2', 's2 is now its own tile');

// n=3: only slot0 accepts edges
assert(allowedEdges(l3, l3.tiles[1].id).length === 0, 'n3 non-full tile rejects edges');
assert(allowedEdges(l3, l3.tiles[0].id).join() === 'top,bottom', 'n3 full tile accepts cross edges');

// 3 -> 4 : split the full tile (slot0). Full tile currently B=[s1]; give it 2 tabs first.
const l3b = layout(
  [tile('B', ['s1', 's9']), tile('C', ['s3']), tile('D', ['s4'])],
  'h',
);
const l4 = splitOut(l3b, 's9', 'B', 'bottom');
assert(l4.tiles.length === 4, '3->4 makes 4 tiles');
assert(l4.tiles[0].id === 'B' && l4.tiles[2].tabs.join() === 's9', '3->4 h: [TL=B, TR, BL=moved, BR]');

// 4 -> reject further splits
assert(splitOut(l4, 's3', l4.tiles[1].id, 'right') === l4, 'no 5th tile');
assert(allowedEdges(l4, l4.tiles[0].id).length === 0, 'n4 allows no edges');

// moveTab: center-drop s1 from B into C
const moved = moveTab(l4, 's1', l4.tiles[1].id);
assert(tileOf(moved, 's1')!.id === l4.tiles[1].id, 'moveTab relocates tab');

// moveTab that empties source collapses it
const two = layout([tile('A', ['s1']), tile('B', ['s2'])]);
const collapsed = moveTab(two, 's1', 'B');
assert(collapsed.tiles.length === 1 && collapsed.tiles[0].id === 'B', 'moveTab collapses emptied source');

console.log('OK operations');
