package architecture

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// BudgetConfigFile is the repo-root config shared by the Go gate and the
// frontend guard in frontend/src/architecture.test.ts. One file, one set of
// numbers: a limit that disagrees across languages is a limit nobody trusts.
const BudgetConfigFile = "code-budgets.json"

// minExemptionReason is long enough that "wiring" or "too big to split" does
// not pass. An exemption is a permanent decision and has to read like one.
const minExemptionReason = 40

// BudgetConfig is the parsed code-budgets.json.
type BudgetConfig struct {
	Limits     Limits     `json:"limits"`
	Exemptions Exemptions `json:"exemptions"`
	Baseline   Baseline   `json:"baseline"`
}

// Limits are the numbers new code must meet.
type Limits struct {
	Go     FileLimit   `json:"go"`
	TS     FileLimit   `json:"ts"`
	Svelte SvelteLimit `json:"svelte"`
	GoFunc FuncLimit   `json:"goFunc"`
	TSFunc FuncLimit   `json:"tsFunc"`
}

type FileLimit struct {
	MaxCodeLines int `json:"maxCodeLines"`
}

// SvelteLimit splits a component's budget because markup and CSS inflate the
// total without being the part that rots. The script block is where logic
// accumulates, so it carries the tighter number.
type SvelteLimit struct {
	MaxScriptCodeLines int `json:"maxScriptCodeLines"`
	MaxTotalCodeLines  int `json:"maxTotalCodeLines"`
}

type FuncLimit struct {
	MaxCodeLines int `json:"maxCodeLines"`
	MaxParams    int `json:"maxParams"`
	MaxNesting   int `json:"maxNesting"`
}

// Exemptions are permanent, reviewed opt-outs. They are deliberately kept in a
// different list from Baseline: an exemption says "this shape is correct and
// will never shrink", a baseline says "this is debt, frozen until someone pays
// it". Merging them would let debt hide behind a justification nobody rechecks.
type Exemptions struct {
	Files     []FileExemption `json:"files"`
	Functions []FuncExemption `json:"functions"`
}

type FileExemption struct {
	Path   string `json:"path"`
	Kind   string `json:"kind"`
	Reason string `json:"reason"`
}

type FuncExemption struct {
	Symbol string `json:"symbol"`
	Kind   string `json:"kind"`
	Reason string `json:"reason"`
}

// Baseline is machine-generated debt, regenerated by `go run ./scripts/budgets
// -update`. Every number may only go down.
type Baseline struct {
	Files     map[string]FileMeasurement `json:"files"`
	Functions map[string]FuncMeasurement `json:"functions"`
}

type FileMeasurement struct {
	CodeLines       int `json:"codeLines"`
	ScriptCodeLines int `json:"scriptCodeLines,omitempty"`
}

type FuncMeasurement struct {
	CodeLines int `json:"codeLines"`
	Params    int `json:"params"`
	Nesting   int `json:"nesting"`
}

// fileExemptionKinds is a closed set. A free-text kind would let "misc" absorb
// everything the rule was written to catch.
var fileExemptionKinds = map[string]string{
	"composition-root": "dependency injection wiring; splitting it only scatters the graph",
	"facade-surface":   "thin delegating methods a framework must see as one type",
	"port-surface":     "declarations only - interfaces, types, constants - with no logic",
	"generated":        "produced by a tool; edit the generator instead",
	"data-table":       "a long literal table where each entry is one line of data",
}

var funcExemptionKinds = map[string]string{
	"composition-root": "dependency injection wiring; splitting it only scatters the graph",
	"dispatch-table":   "a flat switch over a protocol surface, one short arm per case",
	"generated":        "produced by a tool; edit the generator instead",
}

// LoadBudgetConfig reads and validates code-budgets.json.
func LoadBudgetConfig(repoRoot string) (BudgetConfig, error) {
	path := filepath.Join(repoRoot, BudgetConfigFile)
	data, err := os.ReadFile(path)
	if err != nil {
		return BudgetConfig{}, fmt.Errorf("read %s: %w", BudgetConfigFile, err)
	}

	var cfg BudgetConfig
	decoder := json.NewDecoder(strings.NewReader(string(data)))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&cfg); err != nil {
		return BudgetConfig{}, fmt.Errorf("parse %s: %w", BudgetConfigFile, err)
	}
	if err := cfg.validate(); err != nil {
		return BudgetConfig{}, fmt.Errorf("%s: %w", BudgetConfigFile, err)
	}
	return cfg, nil
}

func (c BudgetConfig) validate() error {
	if err := c.validateLimits(); err != nil {
		return err
	}
	seen := map[string]bool{}
	for _, e := range c.Exemptions.Files {
		entry := exemptionEntry{what: "file", id: e.Path, kind: e.Kind, reason: e.Reason}
		if err := validateExemption(entry, fileExemptionKinds, seen); err != nil {
			return err
		}
		if _, dup := c.Baseline.Files[e.Path]; dup {
			return fmt.Errorf("%s is both exempted and baselined; it is either a permanent shape or debt, not both", e.Path)
		}
	}
	seen = map[string]bool{}
	for _, e := range c.Exemptions.Functions {
		entry := exemptionEntry{what: "function", id: e.Symbol, kind: e.Kind, reason: e.Reason}
		if err := validateExemption(entry, funcExemptionKinds, seen); err != nil {
			return err
		}
		if _, dup := c.Baseline.Functions[e.Symbol]; dup {
			return fmt.Errorf("%s is both exempted and baselined; it is either a permanent shape or debt, not both", e.Symbol)
		}
	}
	return nil
}

func (c BudgetConfig) validateLimits() error {
	positives := map[string]int{
		"limits.go.maxCodeLines":           c.Limits.Go.MaxCodeLines,
		"limits.ts.maxCodeLines":           c.Limits.TS.MaxCodeLines,
		"limits.svelte.maxScriptCodeLines": c.Limits.Svelte.MaxScriptCodeLines,
		"limits.svelte.maxTotalCodeLines":  c.Limits.Svelte.MaxTotalCodeLines,
		"limits.goFunc.maxCodeLines":       c.Limits.GoFunc.MaxCodeLines,
		"limits.goFunc.maxParams":          c.Limits.GoFunc.MaxParams,
		"limits.goFunc.maxNesting":         c.Limits.GoFunc.MaxNesting,
		"limits.tsFunc.maxCodeLines":       c.Limits.TSFunc.MaxCodeLines,
		"limits.tsFunc.maxParams":          c.Limits.TSFunc.MaxParams,
		"limits.tsFunc.maxNesting":         c.Limits.TSFunc.MaxNesting,
	}
	names := make([]string, 0, len(positives))
	for name := range positives {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		if positives[name] <= 0 {
			return fmt.Errorf("%s must be a positive number", name)
		}
	}
	return nil
}

// exemptionEntry is the language-neutral view of one exemption, so file and
// function entries share a single set of rules instead of drifting apart.
type exemptionEntry struct {
	what   string
	id     string
	kind   string
	reason string
}

func validateExemption(e exemptionEntry, kinds map[string]string, seen map[string]bool) error {
	if e.id == "" {
		return fmt.Errorf("%s exemption with an empty path/symbol", e.what)
	}
	if seen[e.id] {
		return fmt.Errorf("duplicate %s exemption for %s", e.what, e.id)
	}
	seen[e.id] = true

	if e.kind == "debt" {
		return fmt.Errorf("%s: %q is not an exemption kind. Debt belongs in baseline, where it can only shrink; run `go run ./scripts/budgets -update`", e.id, e.kind)
	}
	if _, ok := kinds[e.kind]; !ok {
		return fmt.Errorf("%s: unknown exemption kind %q. Allowed: %s", e.id, e.kind, strings.Join(sortedKeys(kinds), ", "))
	}
	if len(strings.TrimSpace(e.reason)) < minExemptionReason {
		return fmt.Errorf("%s: exemption reason must be at least %d characters and explain why the shape is correct, not that it is large", e.id, minExemptionReason)
	}
	return nil
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// ExemptFiles indexes the file exemptions by path.
func (c BudgetConfig) ExemptFiles() map[string]FileExemption {
	out := make(map[string]FileExemption, len(c.Exemptions.Files))
	for _, e := range c.Exemptions.Files {
		out[e.Path] = e
	}
	return out
}

// ExemptFunctions indexes the function exemptions by symbol.
func (c BudgetConfig) ExemptFunctions() map[string]FuncExemption {
	out := make(map[string]FuncExemption, len(c.Exemptions.Functions))
	for _, e := range c.Exemptions.Functions {
		out[e.Symbol] = e
	}
	return out
}
