// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';
import {usecase} from '../models';

export function AddKnownHost(arg1:string,arg2:string):Promise<void>;

export function CancelTransfer(arg1:string):Promise<void>;

export function ClearAuditLog():Promise<void>;

export function CloseSession(arg1:string):Promise<void>;

export function CreateFilePath(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateLocalFile(arg1:string):Promise<void>;

export function DeleteAuditEntry(arg1:number):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeletePassword(arg1:string):Promise<void>;

export function DeleteVPNProfile(arg1:string):Promise<void>;

export function Download(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetAllConnections():Promise<Array<wails.ConnectionDTO>>;

export function GetFolders():Promise<Array<wails.FolderDTO>>;

export function GetIdentities():Promise<Array<wails.IdentityDTO>>;

export function GetKnownHosts():Promise<Array<wails.KnownHostDTO>>;

export function GetPingResults():Promise<Array<usecase.PingResult>>;

export function GetPlatform():Promise<string>;

export function GetSessionState(arg1:string):Promise<wails.SessionDTO>;

export function GetSettings():Promise<wails.AppSettingsDTO>;

export function GetTempDir():Promise<string>;

export function GetUserHomeDir():Promise<string>;

export function GetVPNProfile(arg1:string):Promise<wails.VPNProfileDTO>;

export function GetVPNProfiles():Promise<Array<wails.VPNProfileDTO>>;

export function ImportIdentity(arg1:string,arg2:string):Promise<string>;

export function ImportPassword(arg1:string,arg2:string):Promise<string>;

export function ImportPuTTYPPK(arg1:string,arg2:string):Promise<string>;

export function ImportPuTTYReg(arg1:string):Promise<Array<wails.PuTTYSessionDTO>>;

export function ImportPuTTYRegAsConnections(arg1:string,arg2:string):Promise<Array<wails.ConnectionDTO>>;

export function ImportVPNProfile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function IsVaultUnlocked():Promise<boolean>;

export function ListLocalPath(arg1:string,arg2:boolean):Promise<Array<wails.LocalNodeDTO>>;

export function ListPath(arg1:string,arg2:string):Promise<Array<wails.RemoteNodeDTO>>;

export function LockVault():Promise<void>;

export function MkdirLocalPath(arg1:string):Promise<void>;

export function MkdirPath(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MoveConnections(arg1:Array<string>,arg2:string):Promise<void>;

export function MoveFolder(arg1:string,arg2:string):Promise<void>;

export function OpenFileWithSystem(arg1:string,arg2:string):Promise<void>;

export function OpenSession(arg1:string):Promise<string>;

export function PingConnection(arg1:string):Promise<void>;

export function RDPFocusWindow(arg1:string):Promise<void>;

export function RDPStart(arg1:string):Promise<string>;

export function RDPStop(arg1:string):Promise<void>;

export function RemoveKnownHost(arg1:string):Promise<void>;

export function RemoveLocalPath(arg1:string):Promise<void>;

export function RemovePath(arg1:string,arg2:string):Promise<void>;

export function RenameLocalPath(arg1:string,arg2:string):Promise<void>;

export function RenamePath(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReorderConnections(arg1:Array<string>,arg2:string):Promise<void>;

export function ReorderFolders(arg1:Array<string>,arg2:string):Promise<void>;

export function ReportActivity():Promise<void>;

export function ReportMinimized():Promise<void>;

export function ReportRestored():Promise<void>;

export function ResolveHostKey(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveConnection(arg1:wails.ConnectionDTO):Promise<wails.ConnectionDTO>;

export function SaveFolder(arg1:wails.FolderDTO):Promise<wails.FolderDTO>;

export function SaveSettings(arg1:wails.AppSettingsDTO):Promise<void>;

export function SearchAuditLog(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<Array<wails.AuditEntryDTO>>;

export function SelectLocalDirectory():Promise<string>;

export function SelectLocalFile():Promise<string>;

export function SendTerminalInput(arg1:string,arg2:string):Promise<void>;

export function StartFileWatch(arg1:string):Promise<void>;

export function TerminalResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function UnlockVault(arg1:string):Promise<void>;

export function Upload(arg1:string,arg2:string,arg3:string):Promise<void>;
