// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKnownHost(arg1, arg2) {
  return window['go']['main']['App']['AddKnownHost'](arg1, arg2);
}

export function CancelTransfer(arg1) {
  return window['go']['main']['App']['CancelTransfer'](arg1);
}

export function ClearAuditLog() {
  return window['go']['main']['App']['ClearAuditLog']();
}

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function CreateFilePath(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateFilePath'](arg1, arg2, arg3);
}

export function CreateLocalFile(arg1) {
  return window['go']['main']['App']['CreateLocalFile'](arg1);
}

export function DeleteAuditEntry(arg1) {
  return window['go']['main']['App']['DeleteAuditEntry'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeletePassword(arg1) {
  return window['go']['main']['App']['DeletePassword'](arg1);
}

export function DeleteVPNProfile(arg1) {
  return window['go']['main']['App']['DeleteVPNProfile'](arg1);
}

export function Download(arg1, arg2, arg3) {
  return window['go']['main']['App']['Download'](arg1, arg2, arg3);
}

export function GetAllConnections() {
  return window['go']['main']['App']['GetAllConnections']();
}

export function GetFolders() {
  return window['go']['main']['App']['GetFolders']();
}

export function GetIdentities() {
  return window['go']['main']['App']['GetIdentities']();
}

export function GetKnownHosts() {
  return window['go']['main']['App']['GetKnownHosts']();
}

export function GetPingResults() {
  return window['go']['main']['App']['GetPingResults']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetSessionState(arg1) {
  return window['go']['main']['App']['GetSessionState'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTempDir() {
  return window['go']['main']['App']['GetTempDir']();
}

export function GetUserHomeDir() {
  return window['go']['main']['App']['GetUserHomeDir']();
}

export function GetVPNProfile(arg1) {
  return window['go']['main']['App']['GetVPNProfile'](arg1);
}

export function GetVPNProfiles() {
  return window['go']['main']['App']['GetVPNProfiles']();
}

export function ImportIdentity(arg1, arg2) {
  return window['go']['main']['App']['ImportIdentity'](arg1, arg2);
}

export function ImportPassword(arg1, arg2) {
  return window['go']['main']['App']['ImportPassword'](arg1, arg2);
}

export function ImportPuTTYPPK(arg1, arg2) {
  return window['go']['main']['App']['ImportPuTTYPPK'](arg1, arg2);
}

export function ImportPuTTYReg(arg1) {
  return window['go']['main']['App']['ImportPuTTYReg'](arg1);
}

export function ImportPuTTYRegAsConnections(arg1, arg2) {
  return window['go']['main']['App']['ImportPuTTYRegAsConnections'](arg1, arg2);
}

export function ImportVPNProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportVPNProfile'](arg1, arg2, arg3);
}

export function IsVaultUnlocked() {
  return window['go']['main']['App']['IsVaultUnlocked']();
}

export function ListLocalPath(arg1, arg2) {
  return window['go']['main']['App']['ListLocalPath'](arg1, arg2);
}

export function ListPath(arg1, arg2) {
  return window['go']['main']['App']['ListPath'](arg1, arg2);
}

export function LockVault() {
  return window['go']['main']['App']['LockVault']();
}

export function MkdirLocalPath(arg1) {
  return window['go']['main']['App']['MkdirLocalPath'](arg1);
}

export function MkdirPath(arg1, arg2, arg3) {
  return window['go']['main']['App']['MkdirPath'](arg1, arg2, arg3);
}

export function MoveConnections(arg1, arg2) {
  return window['go']['main']['App']['MoveConnections'](arg1, arg2);
}

export function MoveFolder(arg1, arg2) {
  return window['go']['main']['App']['MoveFolder'](arg1, arg2);
}

export function OpenFileWithSystem(arg1, arg2) {
  return window['go']['main']['App']['OpenFileWithSystem'](arg1, arg2);
}

export function OpenSession(arg1) {
  return window['go']['main']['App']['OpenSession'](arg1);
}

export function PingConnection(arg1) {
  return window['go']['main']['App']['PingConnection'](arg1);
}

export function RDPFocusWindow(arg1) {
  return window['go']['main']['App']['RDPFocusWindow'](arg1);
}

export function RDPStart(arg1) {
  return window['go']['main']['App']['RDPStart'](arg1);
}

export function RDPStop(arg1) {
  return window['go']['main']['App']['RDPStop'](arg1);
}

export function RemoveKnownHost(arg1) {
  return window['go']['main']['App']['RemoveKnownHost'](arg1);
}

export function RemoveLocalPath(arg1) {
  return window['go']['main']['App']['RemoveLocalPath'](arg1);
}

export function RemovePath(arg1, arg2) {
  return window['go']['main']['App']['RemovePath'](arg1, arg2);
}

export function RenameLocalPath(arg1, arg2) {
  return window['go']['main']['App']['RenameLocalPath'](arg1, arg2);
}

export function RenamePath(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenamePath'](arg1, arg2, arg3);
}

export function ReorderConnections(arg1, arg2) {
  return window['go']['main']['App']['ReorderConnections'](arg1, arg2);
}

export function ReorderFolders(arg1, arg2) {
  return window['go']['main']['App']['ReorderFolders'](arg1, arg2);
}

export function ReportActivity() {
  return window['go']['main']['App']['ReportActivity']();
}

export function ReportMinimized() {
  return window['go']['main']['App']['ReportMinimized']();
}

export function ReportRestored() {
  return window['go']['main']['App']['ReportRestored']();
}

export function ResolveHostKey(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ResolveHostKey'](arg1, arg2, arg3, arg4);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveFolder(arg1) {
  return window['go']['main']['App']['SaveFolder'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchAuditLog(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SearchAuditLog'](arg1, arg2, arg3, arg4, arg5);
}

export function SelectLocalDirectory() {
  return window['go']['main']['App']['SelectLocalDirectory']();
}

export function SelectLocalFile() {
  return window['go']['main']['App']['SelectLocalFile']();
}

export function SendTerminalInput(arg1, arg2) {
  return window['go']['main']['App']['SendTerminalInput'](arg1, arg2);
}

export function StartFileWatch(arg1) {
  return window['go']['main']['App']['StartFileWatch'](arg1);
}

export function TerminalResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['TerminalResize'](arg1, arg2, arg3);
}

export function UnlockVault(arg1) {
  return window['go']['main']['App']['UnlockVault'](arg1);
}

export function Upload(arg1, arg2, arg3) {
  return window['go']['main']['App']['Upload'](arg1, arg2, arg3);
}
